/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum ErrorCode {
    TASK_NOT_FOUND = 'TASK_NOT_FOUND',
    TASK_INVALID_FORMAT = 'TASK_INVALID_FORMAT',
    AUTH_FAILED = 'AUTH_FAILED',
    AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    RULE_FILE_NOT_FOUND = 'RULE_FILE_NOT_FOUND',
    RESPONSE_FILE_NOT_FOUND = 'RESPONSE_FILE_NOT_FOUND',
    BROWSERSTACK_API_ERROR = 'BROWSERSTACK_API_ERROR',
    TEST_CASE_CREATION_FAILED = 'TEST_CASE_CREATION_FAILED',
    INVALID_REQUEST = 'INVALID_REQUEST',
    INVALID_JSON = 'INVALID_JSON',
    MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
